version: "3.3"
services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "DEBUG=0"
      - "DATA_DIR=/app/service/csvs"
    volumes:
      - ./dash-gene-drive-data:/app/service/csvs
    container_name: gene_drive_staging
    ports:
      #TODO: change port mapping
      - "8050:8050"
    restart: unless-stopped