version: "3.3"
services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "DEBUG=0"
      - "DATA_DIR=/app/service/csvs"
      - "ENVIRONMENT=development"
    volumes:
      - ../dash-gene-drive-data:/app/service/csvs
    container_name: gene_drive
    ports:
      - "8050:8050"
    restart: unless-stopped